import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Hero from "./components/Hero";
import Footer from "./components/Footer";
import WhatsAppIcon from "./components/WhatsappIcon";
import { CustomProvider } from "./configs/provider";
import theme from "@/app/theme/theme";


// layout.js or wherever you're setting fonts
import { Comic_Neue } from 'next/font/google';


const comicNeue = Comic_Neue({
  subsets: ['latin'],
  weight: [  '700'], // Specify the weights you need
  
  variable: '--font-comic-neue',
});




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${comicNeue.variable} font-comic antialiased`}
      >
        <CustomProvider>
        <Header />
       
        {children}
        <WhatsAppIcon />
        <Footer />
        </CustomProvider>
      </body>
    </html>
  );
}
